# Generated by Django 2.2.5 on 2019-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Date Time')),
                ('isUTC', models.BooleanField(default=False, verbose_name='Is UTC Time')),
            ],
        ),
    ]
