# Generated by Django 2.2.6 on 2019-10-29 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_datetime', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DateTime',
            new_name='DateTimeRecord',
        ),
    ]
