# Generated by Django 2.2.6 on 2019-10-23 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='autogenerated_filed',
            new_name='autogenerated_field',
        ),
    ]
