from django.db import models

from django.contrib.auth.models import AbstractUser
import uuid

class CustomUser(AbstractUser):
    date_of_birth = models.DateField(null=True)
    state = models.CharField(max_length=50, default='NA')
    country = models.CharField(max_length=50, default='NA')
    autogenerated_filed = models.CharField(null=True, max_length=50)

    def save(self, *args, **kwargs):
        # save random string.
        self.autogenerated_filed = uuid.uuid4()
        super(CustomUser, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'User'
